CREATE TABLE IF NOT EXISTS users ( id INT NOT NULL AUTO_INCREMENT , email VARCHAR(50) NOT NULL , password VARCHAR(50) NOT NULL , salt VARCHAR(50) NOT NULL , PRIMARY KEY (`id`));
CREATE TABLE IF NOT EXISTS version ( version INT NOT NULL );
INSERT INTO version SELECT 0 WHERE NOT EXISTS (SELECT * FROM version);